#!/bin/bash
#########################################################################
# Written by Fabian Ihle, fabi@ihlecloud.de                             #
# Created: 22.03.2020                                                   #
# github: https://github.com/n1tr0-5urf3r/check_fail2ban                #
#                                                                       #
# Displays information per jail                                         #
# Performance data for total blocked IPs                                #
# Shows which IP is banned until when                                   # 
# --------------------------------------------------------------------- #
# Changelog:                                                            #
# 020820 Version 1.01 - adapted to new fail2ban-client version          #
# 181121 Version 1.02 - use variables for binaries everywhere           #
# 160922 Version 1.03 - Shell check conformity                          #
# 130123 Version 1.04 - Some more output on erroneous permission        #
# 240123 Version 1.05 - Fix output in jaillist (thanks to d-stevens)    #
# 061223 Version 1.06 - Reduce number of sudo invocations               #
#                                             (thanks to MarcSchmitzer) #
#########################################################################

# Helper message
print_help() {
    echo "
Usage:
    $0 -w <warn_total> -c <crit_total> -m <minutes> -r <warn_hits> -R <crit_hits> [-j <jaillist>]

Defaults:
    warn_total=10
    crit_total=20
    minutes=60
    warn_hits=5
    crit_hits=10

Examples:
    $0 -m 10 -r 5 -R 10
    $0 -j ssh,postfix
"
}

print_error() {
    echo "ERROR: $1"
    exit 3
}

# Locate binaries
FBIN=$(command -v fail2ban-client)
SUDO=$(command -v sudo)
if [ -z "$FBIN" ]; then print_error "fail2ban-client not found"; fi
if [ -z "$SUDO" ]; then print_error "sudo not found"; fi

# Defaults
WARN_TOTAL=10
CRIT_TOTAL=20
TIME_WINDOW=60
WARN_HITS=5
CRIT_HITS=10

# Parse arguments
while [[ -n "$1" ]]; do
    case "$1" in
        -w) WARN_TOTAL=$2; shift ;;
        -c) CRIT_TOTAL=$2; shift ;;
        -m) TIME_WINDOW=$2; shift ;;
        -r) WARN_HITS=$2; shift ;;
        -R) CRIT_HITS=$2; shift ;;
        -j) MANUAL=true; JAILLIST=$2; shift ;;
        -h) print_help; exit 0 ;;
        *) print_help; print_error "Unknown argument: $1" ;;
    esac
    shift
done

# Get list of jails if not manually specified
if [ "$MANUAL" != true ]; then
    raw_jails=$($SUDO "$FBIN" status | grep "Jail list" | sed 's/`- Jail list://g')
    JAILLIST=$(echo "$raw_jails" | tr -d '\t ' | sed 's/,$//')
fi

# Check fail2ban service
if ! pgrep -x fail2ban-server >/dev/null; then
    echo "CRITICAL: fail2ban NOT running"
    exit 2
fi

TOTALBANS=0
NEW_BANS=0

IFS=',' read -ra JAILS <<< "$JAILLIST"
for JAIL in "${JAILS[@]}"; do
    # Remove leading/trailing whitespace
    JAIL=$(echo "$JAIL" | xargs)
    if $SUDO "$FBIN" status "$JAIL" 2>/dev/null | grep -q "does not exist"; then
        print_error "Jail '$JAIL' not found"
    fi

    # Current bans
    BANS_RAW=$($SUDO "$FBIN" status "$JAIL" | grep "Currently banned" | sed 's/Currently banned://g')
    BANS=$(echo "$BANS_RAW" | tr -cd '0-9')
    TOTALBANS=$((TOTALBANS + BANS))

    # New bans in TIME_WINDOW
    NEW_RAW=$(zgrep "Ban" /var/log/fail2ban.log | awk -v jail="$JAIL" -v mins="$TIME_WINDOW" '
    BEGIN {count=0}
    {
        split($1,d,"-"); split($2,t,":");
        ts=mktime(d[1]" "d[2]" "d[3]" "t[1]" "t[2]" "t[3])
        if ($0 ~ jail && (systime() - ts <= mins*60)) count++
    }
    END {print count}')
    NEW=$(echo "$NEW_RAW" | tr -cd '0-9')
    NEW_BANS=$((NEW_BANS + NEW))
done

OUTPUT="fail2ban running | total_banned=${TOTALBANS};${WARN_TOTAL};${CRIT_TOTAL} new_bans_${TIME_WINDOW}min=${NEW_BANS};${WARN_HITS};${CRIT_HITS}"

# Determine state
if [ "$TOTALBANS" -ge "$CRIT_TOTAL" ] || [ "$NEW_BANS" -ge "$CRIT_HITS" ]; then
    echo "CRITICAL: $OUTPUT"
    exit 2
elif [ "$TOTALBANS" -ge "$WARN_TOTAL" ] || [ "$NEW_BANS" -ge "$WARN_HITS" ]; then
    echo "WARNING: $OUTPUT"
    exit 1
else
    echo "OK: $OUTPUT"
    exit 0
fi
