#!/bin/bash
#########################################################################
# Written by Fabian Ihle, fabi@ihlecloud.de                             #
# Created: 22.03.2020                                                   #
# github: https://github.com/n1tr0-5urf3r/check_fail2ban                #
#                                                                       #
# Displays information per jail                                         #
# Performance data for total blocked IPs                                #
# Shows which IP is banned until when                                   # 
# --------------------------------------------------------------------- #
# Changelog:                                                            #
# 020820 Version 1.01 - adapted to new fail2ban-client version          #
# 181121 Version 1.02 - use variables for binaries everywhere           #
# 160922 Version 1.03 - Shell check conformity                          #
# 130123 Version 1.04 - Some more output on erroneous permission        #
# 240123 Version 1.05 - Fix output in jaillist (thanks to d-stevens)    #
# 061223 Version 1.06 - Reduce number of sudo invocations               #
#                                             (thanks to MarcSchmitzer) #
# 190526 Version 1.07 - Ability to set nagios user                      #
#                                             (thanks to roberthawdown) #
# 300526 Version 1.08 - Re-enable -t flag                               #
#########################################################################

# Helper message
print_help() {
        echo "
                Usage:

                        ./check_fail2ban -h Display this message
                                         -w <warning level> defaults to 10
                                         -c <crit level> defaults to 20
                                         -t Time: Display until when IPs will be banned
                                         -j <jaillist> i.e. comma separated string of jails, i.e. ssh,postfix
                                            Only check those jails
                                         -u <username> defaults to nagios
                Examples:
                        ./check_fail2ban -t -w 5 -c 10 -j ssh,postfix
                        ./check_fail2ban -t
        "
}

print_error() {
        echo -e "Error: $1\\n"
        exit 3
}

is_number() {
        case "$1" in
                ''|*[!0-9]*)
                        return 1
                        ;;
                *)
                        return 0
                        ;;
        esac
}

format_banned_ips() {
        awk '{ for (i=1; i<=NF; i++) print $i }'
}

format_banned_ips_with_time() {
        awk 'NF { ip=$1; if ($0 ~ / = /) { sub(/^.* = /, ""); print ip " until " $0 } else { print } }'
}

# Get binaries
FBIN=$(command -v fail2ban-client)
FBINSERVER=$(command -v fail2ban-server)
SUDO=$(command -v sudo)
if [ -z "$FBIN" ]; then
        print_error "fail2ban-client not found"
fi
if [ -z "$FBINSERVER" ]; then
        print_error "fail2ban-server not found"
fi
if [ -z "$SUDO" ]; then
        print_error "sudo not found. Please install it"
fi


# Parse Arguments
while test -n "$1"; do
    case "$1" in
        -c)
            CRIT=$2
            shift
            ;;
        -h)
            print_help
            exit 3
            ;;
        -w)
            WARN=$2
            shift
            ;;
        -t)
            TIME=true
            ;;
        -j)
            MANUAL=true
            JAILLIST=$2
            shift
            ;;
        -u)
            NAGIOSUSER=$2
            shift
            ;;
        *)
            print_help
            print_error "Unknown argument: $1"
            ;;
    esac
  shift
done

# Check $NAGIOSUSER is set, and if not set default
if [ -z "$NAGIOSUSER" ]; then
        NAGIOSUSER="nagios"
fi

# Check $SUDO permissions
VISUDO=$($SUDO -l -U "$NAGIOSUSER")
if echo "$VISUDO" | grep -q "(root) NOPASSWD: ${FBIN} status$" &&
   echo "$VISUDO" | grep -q "(root) NOPASSWD: ${FBIN} status \*$" &&
   echo "$VISUDO" | grep -q "(root) NOPASSWD: ${FBIN} get \* bantime$" &&
   { [ ! "$TIME" = true ] || echo "$VISUDO" | grep -q "(root) NOPASSWD: ${FBIN} get \* banip --with-time$"; }; then
                :
else
                echo "Not all sudo permissions available! Please refer to documentation."
                echo "If you have set them up, make sure that the command 'sudo -u ${NAGIOSUSER} /usr/lib/nagios/plugins/check_fail2ban -t -w 1 -c 2' correctly displays your jails."
                print_error "If they do not show up, try repairing sudo permissions with the command 'chown root:root /usr/bin/sudo && chmod 4755 /usr/bin/sudo'"
fi

# Get List of Jails
if [ ! "$MANUAL" = true ]; then
        JAILLIST=$(${SUDO} "${FBIN}" status | grep "Jail list" | sed 's/`- Jail list://g' | sed 's/[[:space:]]//g')
fi

# check for running service
ps -aux | grep "${FBINSERVER}" | grep -v grep > /dev/null 2>&1
if [[ "$?" == "0" ]]; then
    :
else
    echo "CRIT: fail2ban NOT running"
    exit 2
fi

# Parse jaillist
TOTALBANS=0
IFS=',' read -ra JAILS <<< "$JAILLIST"
for JAIL in "${JAILS[@]}"; do
        mapfile STATUS < <($SUDO "$FBIN" status "$JAIL")

        if printf "%s" "${STATUS[@]}" | grep -q "does not exist" ; then
                print_error "Jail \"$JAIL\" not found"
        fi
        if [ "$TIME" = true ]; then
                BANNED_IPS=$($SUDO "$FBIN" get "$JAIL" banip --with-time | format_banned_ips_with_time)
        else
                BANNED_IPS=$(printf "%s" "${STATUS[@]}" | grep "Banned IP list:" | sed 's/^.*Banned IP list:[[:space:]]*//g' | format_banned_ips)
        fi

        if [ -z "$BANNED_IPS" ]; then
                BANNED_IPS="none"
        fi

        # Get Amount of bans
        BANS=0
        BANS=$(printf "%s" "${STATUS[@]}" | grep -o "Currently banned:.*" | sed 's/Currently banned:[[:space:]]*//g')
        TOTALBANS=$((TOTALBANS+BANS))

        # Get Bantime for jail
        BANTIME=$($SUDO "$FBIN" get "$JAIL" bantime)

        # Assemble Output
        OUTPUT="$OUTPUT\\n\\nJail: $JAIL\\nBan time: $BANTIME\\nCurrently banned: $BANS\\nBanned IPs:\\n$BANNED_IPS"
done

# Set default values
if [ -z "$CRIT" ]; then
        CRIT=20
fi

if [ -z "$WARN" ]; then
        WARN=10
fi

if ! is_number "$WARN"; then
        print_error "WARN must be a number"
fi

if ! is_number "$CRIT"; then
        print_error "CRIT must be a number"
fi

if [ "$WARN" -ge "$CRIT" ]; then
        print_error "Error: CRIT must be greater than WARN"
fi

# Append additional info
OUTPUT=$(echo -e "$OUTPUT")
SUMMARY="Total banned: $TOTALBANS IPs|banned_IP=${TOTALBANS};${WARN};${CRIT}"

# States
if [ "$TOTALBANS" -ge "$WARN" ] && [ "$TOTALBANS" -lt "$CRIT" ]; then
        echo "WARNING: $SUMMARY$OUTPUT"
        exit 1
elif [ "$TOTALBANS" -ge "$CRIT" ];then
        echo "CRITICAL: $SUMMARY$OUTPUT"
        exit 2
else
        echo "OK: $SUMMARY$OUTPUT"
        exit 0
fi
